### ISSUE TITLE
[FL-21] Tinkerbell boot docker container failed, but err is not caught

### ISSUE THREAD

**Issue by d8660091** [aws/eks-anywhere#3229]
when you create cluster with EKSA and there is an issue with Boots docker container:

```
panic: listen and serve http: listen tcp 10.80.8.22:80: bind: address already in use

goroutine 250 [running]:
github.com/packethost/pkg/log.Logger.Fatal({{0x1834daf?, 0xc000a6ed70?}, 0xc0006946b0?, 0xc0001fdcc0?}, {0x1a7a1e0?, 0xc000a7d2c0}, {0x0, 0x0, 0x0})
        github.com/packethost/pkg@v0.0.0-20210325161133-868299771ae0/log/log.go:121 +0xa6
main.(*BootsHTTPServer).ServeHTTP(0xc0002bcb00, {0xc000d94ea0?, 0xc0004c0570?, 0xc0004c05d0?, 0xc0004c0630?}, {0xc000132070, 0xd}, {0x1813c22, 0x6}, 0xc000da0b60)
        github.com/tinkerbell/boots/cmd/boots/http.go:136 +0xa05
created by main.main
        github.com/tinkerbell/boots/cmd/boots/main.go:219 +0x1c0e
```

 it shows installing Tinkerbell stack successful:
```
2022-08-31T16:10:59.320-0400    V4      Installing Tinkerbell stack on bootstrap cluster
2022-08-31T16:10:59.320-0400    V6      Installing Tinkerbell helm chart
```
Expected behavior: EKSA command should be able to detect Boots container failure

**Comment by panktishah26** [comment]
This issue has been fixed with this PR https://github.com/aws/eks-anywhere/pull/3357 as a part of https://github.com/aws/eks-anywhere/issues/3238. Closing this issue.
