### ISSUE TITLE
Deleting cluster crashes when `Delete package resources` encounters an error

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#4345]
**What happened**:
I created a workload cluster but installing the curated package controller failed due to the mirrored registry in an air-gapped environment. 
```
2022-12-09T02:11:08.178Z	V0	⚠️  Failed to install the optional EKS-A Curated Package Controller. Please try installation again through eksctl after the cluster creation succeeds	{"warning": "creating package bundle controller custom resourceerror: unable to recognize \"STDIN\": no matches for kind \"PackageBundleController\" in version \"packages.eks.amazonaws.com/v1alpha1\"\ntime=\"2022-12-09T02:11:08Z\" level=fatal msg=\"exec failed with exit code 1\"\n"}
```
I deleted the cluster but a panic occurred when deleting package resource. 
```
2022-12-09T02:23:09.887Z	V0	Delete package resources	{"clusterName": "isc-wonkun-wl-1"}
2022-12-09T02:23:09.887Z	V6	Executing command	{"cmd": "/usr/local/bin/docker exec -i eksa_1670552516142036726 kubectl delete pbc isc-wonkun-wl-1 --kubeconfig ./rbxop-isc-wk-mgmt/rbxop-isc-wk-mgmt-eks-a-cluster.kubeconfig --namespace eksa-packages --ignore-not-found=true"}
2022-12-09T02:23:10.736Z	V9	docker	{"stderr": "error: the server doesn't have a resource type \"pbc\"\ntime=\"2022-12-09T02:23:10Z\" level=fatal msg=\"exec failed with exit code 1\"\n"}
2022-12-09T02:23:10.736Z	V-3	odd number of arguments passed as key-value pairs for logging{"ignored key": "deleting package resources for isc-wonkun-wl-1: error: the server doesn't have a resource type \"pbc\"\ntime=\"2022-12-09T02:23:10Z\" level=fatal msg=\"exec failed with exit code 1\"\n"}
2022-12-09T02:23:10.736Z	V4	Tasks completed	{"duration": "1m13.545449891s"}
2022-12-09T02:23:10.736Z	V3	Cleaning up long running container	{"name": "eksa_1670552516142036726"}
2022-12-09T02:23:10.736Z	V6	Executing command	{"cmd": "/usr/local/bin/docker rm -f -v eksa_1670552516142036726"}
panic: odd number of arguments passed as key-value pairs for logging

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0003a5e00?})
	go.uber.org/zap@v1.22.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0006a2340, {0xc0009d4440, 0x1, 0x1})
	go.uber.org/zap@v1.22.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).DPanic(0x348272b?, {0x3537159?, 0x2df3620?}, {0xc0009d4440, 0x1, 0x1})
	go.uber.org/zap@v1.22.0/logger.go:241 +0x59
github.com/go-logr/zapr.(*zapLogger).handleFields(0xc0000ea270, 0x0, {0xc000bfe340, 0x1, 0x40b31d?}, {0x0?, 0x0, 0x1?})
	github.com/go-logr/zapr@v1.2.3/zapr.go:147 +0xd31
github.com/go-logr/zapr.(*zapLogger).Info(0xc0000ea270, 0x0, {0x34ea996?, 0x0?}, {0xc000bfe340, 0x1, 0x1})
	github.com/go-logr/zapr@v1.2.3/zapr.go:210 +0x8d
github.com/go-logr/logr.Logger.Info({{0x39e7020?, 0xc0000ea270?}, 0xc0001b2000?}, {0x34ea996, 0x24}, {0xc000bfe340, 0x1, 0x1})
	github.com/go-logr/logr@v1.2.3/logr.go:261 +0xd0
github.com/aws/eks-anywhere/pkg/logger.Info(...)
	github.com/aws/eks-anywhere/pkg/logger/logger.go:56
github.com/aws/eks-anywhere/pkg/workflows.(*deletePackageResources).Run(0xc0006f0350?, {0x39e3590, 0xc0001b2000}, 0xc00061c1e0)
	github.com/aws/eks-anywhere/pkg/workflows/delete.go:242 +0x1ba
github.com/aws/eks-anywhere/pkg/task.(*taskRunner).RunTask(0xc0005535f0, {0x39e3590, 0xc0001b2000}, 0xc00061c1e0)
	github.com/aws/eks-anywhere/pkg/task/task.go:155 +0x3e3
github.com/aws/eks-anywhere/pkg/workflows.(*Delete).Run(0xc0006afcb0, {0x39e3590, 0xc0001b2000}, 0xc0005535c0, 0xc00036d680, 0x80?, {0x0?, 0x0?})
	github.com/aws/eks-anywhere/pkg/workflows/delete.go:59 +0x22b
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.(*deleteClusterOptions).deleteCluster(0x51ba060, {0x39e3590, 0xc0001b2000})
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/deletecluster.go:129 +0x585
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.glob..func5(0x51939e0, {0xc000409c00?, 0x8?, 0x8?})
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/deletecluster.go:36 +0x72
github.com/spf13/cobra.(*Command).execute(0x51939e0, {0xc000409b80, 0x8, 0x8})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x51984e0)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.5.0/command.go:911
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.Execute()
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/root.go:43 +0x54
main.main()
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/main.go:29 +0x125
```

**What you expected to happen**:
No panic should occur when deleting a cluster

**How to reproduce it (as minimally and precisely as possible)**:
1. Prepare a mirror registry
2. Create a cluster using the registry
3. Delete the cluster

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.12.2
- EKS Distro Release:

**Comment by TerryHowe** [comment]
So, the error I assume was resource does not exist and the PR closes this issue?

**Comment by wongni** [comment]
> So, the error I assume was resource does not exist and the PR closes this issue?

Yes

**Comment by panktishah26** [comment]
@wongni thanks for pointing out and resolving this issue. Closing this ticket.
