### ISSUE TITLE
[bare metal] cli panic when machine ref to cp node doesnt match/exist

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#6039]
**What happened**:
The cli panics under the following scenario. The `kind: Cluster` object, `spec.controlPlaneConfiguration.machineGroupRef.name` is set to a value that doesn't exist/doesn't match a `TinkerbellMachineConfig` in the `mycluster.yaml`.

```bash
eksctl anywhere create cluster mycluster -f mycluster.yaml --unhealthy-machine-timeout 10m --tinkerbell-bootstrap-ip <IP> -z hardware.csv
```

```bash
Performing setup and validations
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2bdf668]

goroutine 1 [running]:
github.com/aws/eks-anywhere/pkg/providers/tinkerbell.(*Provider).MachineConfigs(0xc00043e580, 0x3c30d50?)
	github.com/aws/eks-anywhere/pkg/providers/tinkerbell/tinkerbell.go:266 +0x168
github.com/aws/eks-anywhere/pkg/providers/tinkerbell.(*Provider).SetupAndValidateCreateCluster(0xc00043e580, {0x3c30d50, 0xc000052078}, 0xc000b78040)
	github.com/aws/eks-anywhere/pkg/providers/tinkerbell/create.go:124 +0x1c5
github.com/aws/eks-anywhere/pkg/workflows.(*SetAndValidateTask).providerValidation.func1()
	github.com/aws/eks-anywhere/pkg/workflows/create.go:190 +0xb2
github.com/aws/eks-anywhere/pkg/validations.(*Runner).Run(0xc000dcdb00?)
	github.com/aws/eks-anywhere/pkg/validations/runner.go:24 +0x42
github.com/aws/eks-anywhere/pkg/workflows.(*SetAndValidateTask).Run(0xc000d9f2c0?, {0x3c30d50, 0xc000052078}, 0xc000d9d9e0)
	github.com/aws/eks-anywhere/pkg/workflows/create.go:177 +0x365
github.com/aws/eks-anywhere/pkg/task.(*taskRunner).RunTask(0xc000e085a0, {0x3c30d50, 0xc000052078}, 0xc000d9d9e0)
	github.com/aws/eks-anywhere/pkg/task/task.go:159 +0x463
github.com/aws/eks-anywhere/pkg/workflows.(*Create).Run(0xc00078fc48, {0x3c30d50, 0xc000052078}, 0xc000b78040, {0x3bfc800?, 0xc000dcdaf0}, 0x0?)
	github.com/aws/eks-anywhere/pkg/workflows/create.go:69 +0x312
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.(*createClusterOptions).createCluster(0x5566620, 0x5537540, {0x0?, 0x0?, 0x0?})
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/createcluster.go:184 +0xf0e
github.com/spf13/cobra.(*Command).execute(0x5537540, {0xc00012ed80, 0x9, 0x9})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x553d420)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.Execute()
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/root.go:65 +0x54
main.main()
	github.com/aws/eks-anywhere/cmd/eksctl-anywhere/main.go:29 +0x125
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: `v0.16.0`
- EKS Distro Release:

**Comment by HiteshRepo** [comment]
@jacobweinstock can you please assign this to me? I would like to work on it. Alreadt started [here](https://github.com/aws/eks-anywhere/pull/6171).
