### ISSUE TITLE
failed govc validations: GOVC_URL is not  set or is empty: false

### ISSUE THREAD

**Issue by michaelday008** [aws/eks-anywhere#8960]
**What happened**:
```
$export EKSA_VSPHERE_USERNAME="eksa@vsphere.local"
$export EKSA_VSPHERE_PASSWORD='********'
$ eksctl anywhere create cluster --filename prod-dc1-mgmt-eksa-cluster.yaml -v 9
2024-11-01T17:32:10.157ZV6Executing command{"cmd": "/usr/bin/docker version --format {{.Client.Version}}"}
2024-11-01T17:32:10.190ZV6Executing command{"cmd": "/usr/bin/docker info --format '{{json .MemTotal}}'"}
2024-11-01T17:32:10.372ZV4Reading bundles manifest{"url": "https://anywhere-assets.eks.amazonaws.com/releases/bundles/50/manifest.yaml"}
2024-11-01T17:32:10.402ZV4Using CAPI provider versions{"Core Cluster API": "v1.5.2+aa5216f", "Kubeadm Bootstrap": "v1.5.2+79ab319", "Kubeadm Control Plane": "v1.5.2+f9414f0
", "External etcd Bootstrap": "v1.0.9+4c9d17a", "External etcd Controller": "v1.0.14+500606a", "Cluster API Provider VSphere": "v1.7.0+481f58e"}
2024-11-01T17:32:10.509ZV5Retrier:{"timeout": "2562047h47m16.854775807s", "backoffFactor": null}
2024-11-01T17:32:10.509ZV2Pulling docker image{"image": "public.ecr.aws/eks-anywhere/cli-tools:v0.18.0-eks-a-50"}
2024-11-01T17:32:10.509ZV6Executing command{"cmd": "/usr/bin/docker pull public.ecr.aws/eks-anywhere/cli-tools:v0.18.0-eks-a-50"}
2024-11-01T17:32:11.151ZV5Retry execution successful{"retries": 1, "duration": "642.214177ms"}
2024-11-01T17:32:11.152ZV3Initializing long running container{"name": "eksa_1730482330509753200", "image": "public.ecr.aws/eks-anywhere/cli-tools:v0.18.0-eks-a-50"}
2024-11-01T17:32:11.152ZV6Executing command{"cmd": "/usr/bin/docker run -d --name eksa_1730482330509753200 --network host -w /home/eksadmin/ng911-eksa-iac -v /var/run/do
cker.sock:/var/run/docker.sock -v /home/eksadmin/ng911-eksa-iac:/home/eksadmin/ng911-eksa-iac -v /home/eksadmin/ng911-eksa-iac:/home/eksadmin/ng911-eksa-iac --entrypoint sleep public.ecr.aws
/eks-anywhere/cli-tools:v0.18.0-eks-a-50 infinity"}
2024-11-01T17:32:11.358ZV4Task start{"task_name": "setup-validate"}
2024-11-01T17:32:11.358ZV0Performing setup and validations
2024-11-01T17:32:11.358ZV4Tasks completed{"duration": "192.189µs"}
2024-11-01T17:32:11.358ZV3Logging out from current govc session
2024-11-01T17:32:11.358ZV-2Closer failed{"closerType": "*dependencies.Dependencies", "error": "govc returned error when logging out: failed govc validations: GOVC_URL is not 
set or is empty: false"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x2986857]

goroutine 1 [running]:
github.com/aws/eks-anywhere/pkg/providers/vsphere.SetupEnvVars(0x0)
github.com/aws/eks-anywhere/pkg/providers/vsphere/envars.go:29 +0x157
github.com/aws/eks-anywhere/pkg/providers/vsphere.(*vsphereProvider).SetupAndValidateCreateCluster(0xc000ac4a00, {0x3894470, 0xc00012e010}, 0xc000a1fac0)
github.com/aws/eks-anywhere/pkg/providers/vsphere/vsphere.go:305 +0xc5
github.com/aws/eks-anywhere/pkg/workflows.(*SetAndValidateTask).providerValidation.func1()
github.com/aws/eks-anywhere/pkg/workflows/create.go:190 +0xb2
github.com/aws/eks-anywhere/pkg/validations.(*Runner).Run(0xc0004fe2e8?)
github.com/aws/eks-anywhere/pkg/validations/runner.go:24 +0x42
github.com/aws/eks-anywhere/pkg/workflows.(*SetAndValidateTask).Run(0xc000aed410?, {0x3894470, 0xc00012e010}, 0xc000af3c20)
github.com/aws/eks-anywhere/pkg/workflows/create.go:177 +0x365
github.com/aws/eks-anywhere/pkg/task.(*taskRunner).RunTask(0xc000b16270, {0x3894470, 0xc00012e010}, 0xc000af3c20)
github.com/aws/eks-anywhere/pkg/task/task.go:159 +0x463
github.com/aws/eks-anywhere/pkg/workflows.(*Create).Run(0xc000b97c50, {0x3894470, 0xc00012e010}, 0xc000a1fac0, {0x385f960?, 0xc0004fe2d8}, 0x0?)
github.com/aws/eks-anywhere/pkg/workflows/create.go:69 +0x312
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.(*createClusterOptions).createCluster(0x5094780, 0x509b780, {0x0?, 0x0?, 0x0?})
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/createcluster.go:256 +0x10fe
github.com/spf13/cobra.(*Command).execute(0x509b780, {0xc0008d40c0, 0x4, 0x4})
github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x50a1940)
github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
github.com/spf13/cobra@v1.6.1/command.go:961
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.Execute()
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd/root.go:65 +0x54
main.main()
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/main.go:29 +0x125
```

**What you expected to happen**: Cluster creation runs successfully

**How to reproduce it (as minimally and precisely as possible)**:  I'm not sure why this is happening.  I've created at least 6 other cluster successfully using this version of EKSA

If I manually set the GOVC_URL variable, then it will ask for GOVC_DATACENTER, and eventually GOVC_INSECURE.  If I set those, then it will skip straight to the segmentation violation without any error messages from govc.

Here is the relevant datacenter section of the yaml file
```
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: prod-dc1-mgmt
spec:
  datacenter: DC1
  insecure: true
  network: /DC1/network/EKSA_managment_network
  server: 10.2.2.18
  thumbprint: ""
```

**Environment**:
- EKS Anywhere Release: v0.18.0
- EKS Distro Release: Ubuntu 22.04 LTS

**Comment by michaelday008** [comment]
Closing this issue.  It's fixed already in EKSA v0.21.0 and now throws a proper error message telling you what part of the yaml file is missing or invalid.
